/*
 * MVKCmdAccelerationStructure.mm
 *
 * Copyright (c) 2015-2026 The Brenwill Workshop Ltd. (http://www.brenwill.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "MVKCmdAccelerationStructure.h"
#include "MVKCommandBuffer.h"
#include "MVKCommandPool.h"
#include "MVKAccelerationStructure.h"
#include "MVKMTLBufferAllocation.h"
#include "MVKDevice.h"

#include <unordered_map>


#pragma mark -
#pragma mark MVKCmdBuildAccelerationStructures

// getTypePool() is generated by MVKCommandTypePools.def (see MVKCommandPool.mm) — do NOT define it here.

// Maps Vulkan per-instance flags to the Metal instance options.
static MTLAccelerationStructureInstanceOptions mvkInstanceOptions(VkGeometryInstanceFlagsKHR flags) {
	MTLAccelerationStructureInstanceOptions opts = MTLAccelerationStructureInstanceOptionNone;
	if (flags & VK_GEOMETRY_INSTANCE_TRIANGLE_FACING_CULL_DISABLE_BIT_KHR) { opts |= MTLAccelerationStructureInstanceOptionDisableTriangleCulling; }
	if (flags & VK_GEOMETRY_INSTANCE_TRIANGLE_FLIP_FACING_BIT_KHR)         { opts |= MTLAccelerationStructureInstanceOptionTriangleFrontFacingWindingCounterClockwise; }
	if (flags & VK_GEOMETRY_INSTANCE_FORCE_OPAQUE_BIT_KHR)                 { opts |= MTLAccelerationStructureInstanceOptionOpaque; }
	if (flags & VK_GEOMETRY_INSTANCE_FORCE_NO_OPAQUE_BIT_KHR)              { opts |= MTLAccelerationStructureInstanceOptionNonOpaque; }
	return opts;
}

VkResult MVKCmdBuildAccelerationStructures::setContent(
	MVKCommandBuffer* cmdBuff,
	uint32_t infoCount,
	const VkAccelerationStructureBuildGeometryInfoKHR* pInfos,
	const VkAccelerationStructureBuildRangeInfoKHR* const* ppBuildRangeInfos) {

	// The command object is pool-recycled — reset the captured state before re-populating (load-bearing).
	_builds.clear();
	_geometries.clear();
	_primitiveCounts.clear();
	_primitiveOffsets.clear();

	for (uint32_t i = 0; i < infoCount; i++) {
		const VkAccelerationStructureBuildGeometryInfoKHR& info = pInfos[i];
		const VkAccelerationStructureBuildRangeInfoKHR* ranges = ppBuildRangeInfos[i];   // one range per geometry

		MVKASBuild b = {};
		b.dst               = (MVKAccelerationStructure*)info.dstAccelerationStructure;
		b.type              = info.type;
		b.mode              = info.mode;
		b.scratchAddress    = info.scratchData.deviceAddress;
		b.firstGeometryIndex = (uint32_t)_geometries.size();
		b.geometryCount     = info.geometryCount;

		// pInfos / ppBuildRangeInfos / pGeometries are caller-owned and may be freed once this call returns;
		// encode() runs later at submit, so deep-copy. For a device build the geometry is value-only
		// (triangle vertexData/stride/format, or instances data.deviceAddress), so a flat struct copy suffices.
		for (uint32_t j = 0; j < info.geometryCount; j++) {
			const VkAccelerationStructureGeometryKHR& g = info.pGeometries ? info.pGeometries[j]
																		  : *info.ppGeometries[j];
			_geometries.push_back(g);
			_primitiveCounts.push_back(ranges[j].primitiveCount);    // lockstep with _geometries
			_primitiveOffsets.push_back(ranges[j].primitiveOffset);  // lockstep with _geometries
		}
		_builds.push_back(b);
	}
	return VK_SUCCESS;
}

void MVKCmdBuildAccelerationStructures::encode(MVKCommandEncoder* cmdEncoder) {
	MVKDevice* dev = cmdEncoder->getDevice();
	for (auto& b : _builds) {
		// The fork always does a full BUILD (no refit). Silently running an UPDATE as a full build would overflow
		// an update-sized scratch (updateScratchSize < buildScratchSize) → GPU fault; fail loud instead. The engine
		// only issues MODE_BUILD (see RtAccelCache); this guards a future/foreign UPDATE.
		if (b.mode != VK_BUILD_ACCELERATION_STRUCTURE_MODE_BUILD_KHR) {
			MVKLogError("vkCmdBuildAccelerationStructuresKHR: build mode %d (refit/UPDATE) is unsupported by the VulkanEd "
						"fork — only VK_BUILD_ACCELERATION_STRUCTURE_MODE_BUILD_KHR; skipping this build.", (int)b.mode);
			continue;
		}
		if      (b.type == VK_ACCELERATION_STRUCTURE_TYPE_BOTTOM_LEVEL_KHR) { encodeBLAS(cmdEncoder, dev, b); }
		else if (b.type == VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_KHR)    { encodeTLAS(cmdEncoder, dev, b); }
	}
}

void MVKCmdBuildAccelerationStructures::encodeBLAS(MVKCommandEncoder* cmdEncoder, MVKDevice* dev, const MVKASBuild& b) {
	if (b.geometryCount == 0) { return; }
	if ( !b.dst || !b.dst->getMTLAccelerationStructure() ) { return; }

	// Rebuild a Vulkan build-info view over this build's captured, contiguous geometry slice, then reuse the
	// shared descriptor builder (same one BuildSizes used — guarantees the built AS matches the alloc size).
	VkAccelerationStructureBuildGeometryInfoKHR info = {};
	info.sType         = VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_BUILD_GEOMETRY_INFO_KHR;
	info.type          = b.type;
	info.geometryCount = b.geometryCount;
	info.pGeometries   = &_geometries[b.firstGeometryIndex];

	MTLAccelerationStructureDescriptor* desc =
		MVKAccelerationStructure::getMTLDescriptor(dev, &info, &_primitiveCounts[b.firstGeometryIndex]);

	NSUInteger scratchOffset = 0;
	id<MTLBuffer> scratch = dev->getMTLBufferForDeviceAddress(b.scratchAddress, &scratchOffset);
	if ( !scratch ) {
		MVKLogError("vkCmdBuildAccelerationStructuresKHR: BLAS scratch buffer (device address 0x%llx) not found — BLAS build skipped.",
					(unsigned long long)b.scratchAddress);
		return;
	}

	id<MTLAccelerationStructureCommandEncoder> enc =
		cmdEncoder->getMTLAccelerationStructureEncoder(kMVKCommandUseBuildAccelerationStructure);
	[enc buildAccelerationStructure: b.dst->getMTLAccelerationStructure()
						 descriptor: desc
					  scratchBuffer: scratch
				scratchBufferOffset: scratchOffset];

	MVKLogInfo("[VulkanEd fork] encoded BLAS build (%u geometr%s).", b.geometryCount, b.geometryCount == 1 ? "y" : "ies");
}

void MVKCmdBuildAccelerationStructures::encodeTLAS(MVKCommandEncoder* cmdEncoder, MVKDevice* dev, const MVKASBuild& b) {
	if (b.geometryCount == 0) { return; }
	if ( !b.dst || !b.dst->getMTLAccelerationStructure() ) { return; }

	const VkAccelerationStructureGeometryKHR& g = _geometries[b.firstGeometryIndex];
	if (g.geometryType != VK_GEOMETRY_TYPE_INSTANCES_KHR) { return; }
	uint32_t instanceCount = _primitiveCounts[b.firstGeometryIndex];
	uint32_t byteOffset    = _primitiveOffsets[b.firstGeometryIndex];
	if (instanceCount == 0) { return; }

	// Host-read the Vulkan instance array. The engine's instance buffer is host-visible/coherent → Shared
	// storage on Apple GPUs, so [contents] is a valid CPU pointer at encode time.
	NSUInteger instOff = 0;
	id<MTLBuffer> instBuf = dev->getMTLBufferForDeviceAddress(g.geometry.instances.data.deviceAddress, &instOff);
	if ( !instBuf || !instBuf.contents ) {
		MVKLogError("vkCmdBuildAccelerationStructuresKHR: TLAS instance buffer (device address 0x%llx) not host-readable — TLAS build skipped.",
					(unsigned long long)g.geometry.instances.data.deviceAddress);
		return;
	}
	auto* vkInsts = (const VkAccelerationStructureInstanceKHR*)((uintptr_t)instBuf.contents + instOff + byteOffset);

	// Translate Vulkan instances → Metal instance descriptors, in order (the shader indexes hits by
	// CommittedInstanceIndex == build order), deduping the referenced BLAS into instancedAccelerationStructures.
	const MVKMTLBufferAllocation* tmp = cmdEncoder->getTempMTLBuffer(instanceCount * sizeof(MTLAccelerationStructureInstanceDescriptor));
	auto* mtlInsts = (MTLAccelerationStructureInstanceDescriptor*)tmp->getContents();

	NSMutableArray<id<MTLAccelerationStructure>>* blasArray = [NSMutableArray array];
	std::unordered_map<MVKAccelerationStructure*, uint32_t> blasIndex;
	b.dst->getReferencedBLAS().clear();

	for (uint32_t i = 0; i < instanceCount; i++) {
		const VkAccelerationStructureInstanceKHR& vi = vkInsts[i];
		// Pointer-as-token: accelerationStructureReference IS the MVKAccelerationStructure* (see
		// vkGetAccelerationStructureDeviceAddressKHR). TRUSTED INPUT — a garbage/stale value is a wild deref; the
		// getVkObjectType() check below catches type-confusion but not use-after-free (a real address→AS registry
		// would; deferred). The engine only writes live BLAS handles.
		auto* blas = (MVKAccelerationStructure*)vi.accelerationStructureReference;
		if ( !blas || blas->getVkObjectType() != VK_OBJECT_TYPE_ACCELERATION_STRUCTURE_KHR || !blas->getMTLAccelerationStructure() ) {
			MVKLogError("vkCmdBuildAccelerationStructuresKHR: TLAS instance %u has an invalid/unbuilt BLAS reference — TLAS build skipped.", i);
			return;
		}

		uint32_t asIndex;
		auto it = blasIndex.find(blas);
		if (it != blasIndex.end()) {
			asIndex = it->second;
		} else {
			asIndex = (uint32_t)blasArray.count;
			blasIndex[blas] = asIndex;
			[blasArray addObject: blas->getMTLAccelerationStructure()];
			b.dst->getReferencedBLAS().push_back(blas);   // for M2c compute-dispatch residency
		}

		MTLAccelerationStructureInstanceDescriptor& md = mtlInsts[i];
		// Vk VkTransformMatrixKHR is 3x4 row-major (matrix[row][col]); Metal MTLPackedFloat4x3 is 4 columns of
		// float3 — the same affine in column-major storage: columns[c] = (matrix[0][c], matrix[1][c], matrix[2][c]).
		for (int c = 0; c < 4; c++) {
			md.transformationMatrix.columns[c].x = vi.transform.matrix[0][c];
			md.transformationMatrix.columns[c].y = vi.transform.matrix[1][c];
			md.transformationMatrix.columns[c].z = vi.transform.matrix[2][c];
		}
		md.options                         = mvkInstanceOptions(vi.flags);
		md.mask                            = vi.mask;
		md.intersectionFunctionTableOffset = 0;   // inline ray-query has no shader binding table
		md.accelerationStructureIndex      = asIndex;
	}

	auto* d = [MTLInstanceAccelerationStructureDescriptor descriptor];
	d.instanceCount                   = instanceCount;
	d.instanceDescriptorType          = MTLAccelerationStructureInstanceDescriptorTypeDefault;
	d.instanceDescriptorBuffer        = tmp->_mtlBuffer;
	d.instanceDescriptorBufferOffset  = tmp->_offset;
	d.instanceDescriptorStride        = sizeof(MTLAccelerationStructureInstanceDescriptor);
	d.instancedAccelerationStructures = blasArray;

	NSUInteger scratchOffset = 0;
	id<MTLBuffer> scratch = dev->getMTLBufferForDeviceAddress(b.scratchAddress, &scratchOffset);
	if ( !scratch ) {
		MVKLogError("vkCmdBuildAccelerationStructuresKHR: TLAS scratch buffer (device address 0x%llx) not found — TLAS build skipped.",
					(unsigned long long)b.scratchAddress);
		return;
	}

	id<MTLAccelerationStructureCommandEncoder> enc =
		cmdEncoder->getMTLAccelerationStructureEncoder(kMVKCommandUseBuildAccelerationStructure);
	[enc buildAccelerationStructure: b.dst->getMTLAccelerationStructure()
						 descriptor: d
					  scratchBuffer: scratch
				scratchBufferOffset: scratchOffset];

	MVKLogInfo("[VulkanEd fork] encoded TLAS build (%u instances, %lu BLAS).", instanceCount, (unsigned long)blasArray.count);
}
